#==============================================
# EffectiveFlyByTemplate BBH population prior
#==============================================

#=================================
# INTRINSIC PARAMETERS
#=================================
parameters:
  
  intrinsic:

    m1:
      distribution: "uniform"
      kwargs:
        minimum: 10.0
        maximum: 100.0
      
    m2:
      distribution: "uniform"
      kwargs:
        minimum: 10.0
        maximum: 100.0
    
    e0:
      distribution: "uniform"
      kwargs:
        minimum: 0.65
        maximum: 0.95

    p_0:
      distribution: "uniform"
      kwargs:
        minimum: 8.0
        maximum: 20.0

    polarization:
      distribution: "uniform"
      kwargs:
        minimum: 0.0
        maximum: torch.pi

    inclination:
      distribution: "sin"
      kwargs:
        minimum: 0.0
        maximum: torch.pi


#=================================
# EXTRINSIC PARAMETERS
#=================================
  extrinsic:

    time_shift:
      distribution: "uniform"
      kwargs:
        minimum: -0.25
        maximum: 0.25

    luminosity_distance:
      distribution: "uniform"
      kwargs:
        minimum: 10
        maximum: 2000

    ra:
      distribution: "uniform"
      kwargs:
        minimum: 0.0
        maximum: 2 * torch.pi
      
    dec:
      distribution: "cos"
      kwargs:
        minimum: -torch.pi / 2
        maximum:  torch.pi / 2
