###############################################
# EffectiveFlyByTemplate BBH population prior
###############################################
reference_gps_time: 1370692818

fs : 2048

parameters:

  m1:
    distribution: "uniform"
    kwargs:
      minimum: 10.0
      maximum: 150.0
    

  m2:
    distribution: "uniform"
    kwargs:
      minimum: 10.0
      maximum: 150.0
  
  e0:
    distribution: "uniform"
    kwargs:
      minimum: 0.65
      maximum: 0.95

  p_0:
    distribution: "uniform"
    kwargs:
      minimum: 10.0
      maximum: 25.0

  time_shift:
    distribution: "uniform"
    kwargs:
      minimum: -0.25
      maximum: 0.25

  polarization:
    distribution: "uniform"
    kwargs:
      minimum: 0.0
      maximum: 3.141592653589793

  inclination:
    distribution: "sin"
    kwargs:
      minimum: 0.0
      maximum: 3.141592653589793

  distance:
    distribution: "uniform"
    kwargs:
      minimum: 10
      maximum: 2000

  ra:
    distribution: "uniform"
    kwargs:
      minimum: 0.0
      maximum: 6.283185307179586
    
  dec:
    distribution: "cos"
    kwargs:
      minimum: -1.5707963267948966
      maximum: 1.5707963267948966
