##################################################
######  Configuration Options for HYPERION #######
##################################################

#============================
# SIMULATION & INFERENCE 
#============================
detectors: ["L1", "H1", "V1"]

reference_gps_time: 1370692818 #1242442967.4 #1370692818

fs: 2048 #sampling frequency Hz for simulations & inference 

ASD_reference_run: O3a #reference run for the ASDs

use_reference_asd: true #use the reference run for the ASDs

#inference_parameters: ["M", "q", "e0", "p_0", "distance", "polarization", "inclination", "time_shift", "ra", "dec"]
#inference_parameters: ["M", "q", "e0", "p_0", "distance", "time_shift", "ra", "dec"]

#waveform: "EffectiveFlyByTemplate"
waveform_model: "TEOBResumSDALI"

prior: "TEOBResumS_hyperbolic"

inference_parameters: ["M", "q", "H_hyp", "r_hyp", "j_hyp", "distance", "chi1", "chi2", "inclination", "polarization", "tcoal", "ra", "dec"]

duration: 2 #duration in seconds for the simulated signals


#============================
# FLOW and EMBEDDING NETWORK
#============================
flow:
  num_coupling_layers: 42

coupling_layers:
  num_features:     13
  num_identity:     6
  num_transformed:  7

base_distribution:
  dim:              13
  trainable:        false

embedding_network:
  strain_shape:     [3, None]
  num_blocks:       3
  block_dims:       [2048, 1024, 512, 256]
  strain_out_dim:   256
  use_batch_norm:   true
  dropout_probability: 0.2


#============================
# TRAINING options
#============================
training_options:
  num_epochs: 300

  batch_size: 512

  initial_learning_rate: 0.0001

  steps_per_epoch: 1000

  val_steps_per_epoch: 150

  num_preload_train: 2000
  num_preload_val: 1000

  n_proc: os.cpu_count()

  lr_schedule:
    #scheduler: CosineAnnealingLR
    #kwargs:
    #  T_max: 250 #has to be equal to num_epochs
    
    scheduler: ReduceLROnPlateau
    kwargs:
      factor:    0.5
      patience:  15
      mode:      min
      threshold: 0
    
  optimizer:
    algorithm: Adam

  seeds:
    train:   123
    val:     1234
    test:    12345
  verbose:   true

