##################################################
######  Configuration Options for HYPERION #######
##################################################

#============================
# SIMULATION & INFERENCE 
#============================
detectors: ["L1", "H1", "V1"]

reference_gps_time: 1370692818

fs: 2048 #sampling frequency Hz for simulations & inference 

ASD_reference_run: O3 #reference run for the ASDs

inference_parameters: ["M", "q", "e0", "p_0", "distance", "polarization", "inclination", "time_shift", "ra", "dec"]
#inference_parameters: ["M", "q", "e0", "p_0", "distance", "time_shift", "ra", "dec"]

waveform: "EffectiveFlyByTemplate"

prior: "TEOBResumS_hyperbolic"

#============================
# FLOW and EMBEDDING NETWORK
#============================
flow:
  num_coupling_layers: 32

coupling_layers:
  num_features:     10
  num_identity:     5
  num_transformed:  5

base_distribution:
  dim:              10
  trainable:        true

embedding_network:
  strain_shape:     [3, None]
  num_blocks:       3
  block_dims:       [2048, 1024, 512, 256]
  strain_out_dim:   256
  use_batch_norm:   false
  dropout_probability: 0.2


#============================
# TRAINING options
#============================
training_options:
  num_epochs: 250

  batch_size: 512

  initial_learning_rate: 0.0001

  steps_per_epoch: 1000

  val_steps_per_epoch: 100

  lr_schedule:
    scheduler: CosineAnnealingLR
    kwargs:
      T_max: 250 #has to be equal to num_epochs
    
    #scheduler: ReduceLROnPlateau
    #kwargs:
    #  factor:    0.5
    #  patience:  15
    #  mode:      min
    #  threshold: 0
    
  optimizer:
    algorithm: Adam

  seeds:
    train:   123
    val:     1234
    test:    12345
  verbose:      true

