
###################################
# TEOBResumS BBH population prior
###################################
reference_gps_time: 1370692818
fs : 2048
parameters:

  m1:
    distribution: "uniform"
    min: 10.0
    max: 150.0

  m2:
    distribution: "uniform"
    min: 10.0
    max: 150.0

  ecc:
    distribution: "uniform"
    min: 0.65
    max: 0.95

  time_shift:
    distribution: "uniform"
    min: -0.25
    max: 0.25

  polarization:
    distribution: "uniform"
    min: 0.0
    max: 3.141592653589793

  inclination:
    distribution: "sin"
    min: 0.0
    max: 3.141592653589793

  distance:
    distribution: "uniform"
    min: 10
    max: 2000

  ra:
    distribution: "uniform"
    min: 0.0
    max: 6.283185307179586
    
  dec:
    distribution: "cos"
    min: -1.5707963267948966
    max: 1.5707963267948966
